/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/CS/CSView': RouteRecordInfo<'/CS/CSView', '/CS/CSView', Record<never, never>, Record<never, never>>,
    '/CS/MatchHistoryView': RouteRecordInfo<'/CS/MatchHistoryView', '/CS/MatchHistoryView', Record<never, never>, Record<never, never>>,
    '/DOTA/AccountView': RouteRecordInfo<'/DOTA/AccountView', '/DOTA/AccountView', Record<never, never>, Record<never, never>>,
    '/DOTA/HeroesView': RouteRecordInfo<'/DOTA/HeroesView', '/DOTA/HeroesView', Record<never, never>, Record<never, never>>,
    '/DOTA/MatchDetail': RouteRecordInfo<'/DOTA/MatchDetail', '/DOTA/MatchDetail', Record<never, never>, Record<never, never>>,
    '/DOTA/MatchesView': RouteRecordInfo<'/DOTA/MatchesView', '/DOTA/MatchesView', Record<never, never>, Record<never, never>>,
    '/DOTA/NavBar': RouteRecordInfo<'/DOTA/NavBar', '/DOTA/NavBar', Record<never, never>, Record<never, never>>,
    '/DOTA/RankingsView': RouteRecordInfo<'/DOTA/RankingsView', '/DOTA/RankingsView', Record<never, never>, Record<never, never>>,
    '/DOTA/SearchView': RouteRecordInfo<'/DOTA/SearchView', '/DOTA/SearchView', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/LOL/AccountView': RouteRecordInfo<'/LOL/AccountView', '/LOL/AccountView', Record<never, never>, Record<never, never>>,
    '/LOL/ChampsView': RouteRecordInfo<'/LOL/ChampsView', '/LOL/ChampsView', Record<never, never>, Record<never, never>>,
    '/LOL/LOLSearchView': RouteRecordInfo<'/LOL/LOLSearchView', '/LOL/LOLSearchView', Record<never, never>, Record<never, never>>,
    '/TFT/BuffNerfView': RouteRecordInfo<'/TFT/BuffNerfView', '/TFT/BuffNerfView', Record<never, never>, Record<never, never>>,
    '/TFT/RankingView': RouteRecordInfo<'/TFT/RankingView', '/TFT/RankingView', Record<never, never>, Record<never, never>>,
    '/TFT/SearchView': RouteRecordInfo<'/TFT/SearchView', '/TFT/SearchView', Record<never, never>, Record<never, never>>,
    '/TFT/StatsView': RouteRecordInfo<'/TFT/StatsView', '/TFT/StatsView', Record<never, never>, Record<never, never>>,
    '/ValorantView': RouteRecordInfo<'/ValorantView', '/ValorantView', Record<never, never>, Record<never, never>>,
  }
}
