/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/CSView': RouteRecordInfo<'/CSView', '/CSView', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/LOLView': RouteRecordInfo<'/LOLView', '/LOLView', Record<never, never>, Record<never, never>>,
    '/TFTView': RouteRecordInfo<'/TFTView', '/TFTView', Record<never, never>, Record<never, never>>,
    '/ValorantView': RouteRecordInfo<'/ValorantView', '/ValorantView', Record<never, never>, Record<never, never>>,
  }
}
